# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=11)),
                ('title', models.CharField(max_length=50)),
                ('image_url', models.CharField(max_length=500)),
                ('gender', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=20)),
                ('sale_url', models.CharField(max_length=500)),
                ('keyword', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
